wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.12
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699271776.389896
    t:
      1:
      - 33
      - 55
      - 86
      - 95
      2:
      - 33
      - 55
      - 86
      - 95
      3:
      - 23
      4: 3.10.13
      5: 0.15.12
      8:
      - 4
      - 5
      9:
        2: langchain
      10:
      - 10
      13: darwin-arm64
