wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699109612.049827
    t:
      1:
      - 55
      - 86
      2:
      - 55
      - 86
      - 95
      3:
      - 23
      4: 3.10.12
      5: 0.15.12
      8:
      - 4
      - 5
      13: darwin-arm64
